# Generated by Django 4.2.17 on 2025-03-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0009_tweetdatatrem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdatatrem',
            name='likes',
            field=models.IntegerField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
